#!/bin/sh

usage() {
    echo "Usage: $(basename $0) [options] <remotes>"
    echo ""
    echo "Options:"
    echo "-h,--help"
    echo "--https"
    echo "--ssh"
    exit $1
}

opts=$(getopt --options "hv" --longoptions "help,https,ssh" --name "$(basename $0)" -- "$@")
[ $? -eq 0 ] || usage 1
eval set -- "$opts"

set -e

proto=auto

while true; do
    case "$1" in
        -h|--help)
            usage
            ;;
        --https)
            proto=https
            shift
            ;;
        --ssh)
            proto=ssh
            shift
            ;;
        --)
            shift
            break
            ;;
    esac
done

[ $# -gt 0 ] || usage 1

origin=$(git remote get-url origin)
ssh="git@([^:]+):(.+)"
https="https://([^/]+)/(.+)"

if [[ $origin =~ $ssh ]]; then
    host=${BASH_REMATCH[1]}
    path=${BASH_REMATCH[2]}
    [ $proto = auto ] && proto=ssh
elif [[ $origin =~ $https ]]; then
    host=${BASH_REMATCH[1]}
    path=${BASH_REMATCH[2]}
    [ $proto = auto ] && proto=https
fi
name=$(echo "$path" | cut -d/ -f2)

while [ $# -gt 0 ]; do
    remote="$1"
    path="$remote/$name"

    case "$proto" in
        ssh)
            url="git@$host:$path"
            ;;
        https)
            url="https://$host/$path"
            ;;
    esac

    if ! git remote | grep "$remote" > /dev/null; then
        git remote add "$remote" "$url"
    else
        git remote set-url "$remote" "$url"
    fi
    shift
done

git remote -v
